{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"text":"@rethrows","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Continuable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Success","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Failure","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Use continuations for interfacing Swift tasks with event loops, delegate methods, callbacks,"},{"type":"text","text":" "},{"type":"text","text":"and other non-async scheduling mechanisms."}],"type":"paragraph"}]}],"metadata":{"title":"Continuable","role":"symbol","symbolKind":"protocol","modules":[{"name":"AsyncObjects"}],"externalID":"s:12AsyncObjects11ContinuableP","navigatorTitle":[{"kind":"identifier","text":"Continuable"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Continuable"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncobjects\/continuable"]}],"sections":[],"identifier":{"url":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Associated Types","identifiers":["doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Failure","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Success"]},{"title":"Instance Methods","identifiers":["doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/cancel()-46gpe","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/cancel()-7ca4g","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume()","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(returning:)-655td","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(throwing:)-9qp75","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(with:)"]}],"abstract":[{"type":"text","text":"A type that allows to interface between synchronous and asynchronous code,"},{"type":"text","text":" "},{"type":"text","text":"by representing task state and allowing task resuming with some value or error."}],"hierarchy":{"paths":[["doc:\/\/AsyncObjects\/documentation\/AsyncObjects"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://AsyncObjects/documentation/AsyncObjects/Continuable/Success":{"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Success","title":"Success","required":true,"url":"\/documentation\/asyncobjects\/continuable\/success","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Success"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The type of value to resume the continuation with in case of success."}]},"doc://AsyncObjects/documentation/AsyncObjects/Continuable":{"title":"Continuable","url":"\/documentation\/asyncobjects\/continuable","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Continuable","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A type that allows to interface between synchronous and asynchronous code,","type":"text"},{"text":" ","type":"text"},{"text":"by representing task state and allowing task resuming with some value or error.","type":"text"}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable","navigatorTitle":[{"text":"Continuable","kind":"identifier"}]},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume(with:)":{"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(with:)","title":"resume(with:)","required":true,"url":"\/documentation\/asyncobjects\/continuable\/resume(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Success","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"text":"Failure","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Resume the task awaiting the continuation by having it either return normally","type":"text"},{"text":" ","type":"text"},{"text":"or throw an error based on the state of the given ","type":"text"},{"code":"Result","type":"codeVoice"},{"text":" value.","type":"text"}]},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/cancel()-7ca4g":{"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/cancel()-7ca4g","role":"symbol","abstract":[{"type":"text","text":"Dummy cancellation method for continuations"},{"type":"text","text":" "},{"type":"text","text":"that don’t support cancellation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"type":"topic","title":"cancel()","url":"\/documentation\/asyncobjects\/continuable\/cancel()-7ca4g"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/Failure":{"type":"topic","abstract":[{"text":"The type of error to resume the continuation with in case of failure.","type":"text"}],"kind":"symbol","fragments":[{"text":"associatedtype","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"required":true,"url":"\/documentation\/asyncobjects\/continuable\/failure","role":"symbol","title":"Failure","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Failure"},"doc://AsyncObjects/documentation/AsyncObjects":{"abstract":[{"text":"Several synchronization primitives and task synchronization mechanisms introduced to aid in modern swift concurrency.","type":"text"}],"role":"collection","title":"AsyncObjects","url":"\/documentation\/asyncobjects","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects","kind":"symbol","type":"topic"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/cancel()-46gpe":{"abstract":[{"type":"text","text":"Cancel continuation by resuming with cancellation error."}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Failure","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":".","type":"text"}]},"url":"\/documentation\/asyncobjects\/continuable\/cancel()-46gpe","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/cancel()-46gpe","title":"cancel()"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume(throwing:)-9qp75":{"title":"resume(throwing:)","required":true,"url":"\/documentation\/asyncobjects\/continuable\/resume(throwing:)-9qp75","type":"topic","defaultImplementations":1,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"text":"(","kind":"text"},{"text":"throwing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Failure","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Resume the task awaiting the continuation by having it throw an error from its suspension point.","type":"text"}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(throwing:)-9qp75"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume()":{"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume()","title":"resume()","url":"\/documentation\/asyncobjects\/continuable\/resume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Resume the task that’s awaiting the continuation by returning."}]},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume(returning:)-655td":{"url":"\/documentation\/asyncobjects\/continuable\/resume(returning:)-655td","title":"resume(returning:)","abstract":[{"text":"Resume the task awaiting the continuation by having it return normally from its suspension point.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"returning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Success"},{"kind":"text","text":")"}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(returning:)-655td","type":"topic","required":true,"kind":"symbol","defaultImplementations":1,"role":"symbol"}}}