{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fulfill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"throwing"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error to throw to the callers."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A future must be fulfilled exactly once. If the future has already been fulfilled,"},{"type":"text","text":" "},{"type":"text","text":"then calling this method has no effect and returns immediately."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/asyncobjects\/future\/fulfill(throwing:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Future\/fulfill(throwing:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Terminate the future with the given error and propagate error to subscribers."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fulfill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"throwing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":")"}],"title":"fulfill(throwing:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:12AsyncObjects6FutureC7fulfill8throwingyq__tF","modules":[{"name":"AsyncObjects"}]},"hierarchy":{"paths":[["doc:\/\/AsyncObjects\/documentation\/AsyncObjects","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Future"]]},"references":{"doc://AsyncObjects/documentation/AsyncObjects/Future/fulfill(throwing:)":{"role":"symbol","title":"fulfill(throwing:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fulfill"},{"kind":"text","text":"("},{"kind":"externalParam","text":"throwing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Terminate the future with the given error and propagate error to subscribers."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Future\/fulfill(throwing:)","kind":"symbol","type":"topic","url":"\/documentation\/asyncobjects\/future\/fulfill(throwing:)"},"doc://AsyncObjects/documentation/AsyncObjects":{"role":"collection","title":"AsyncObjects","abstract":[{"type":"text","text":"Several synchronization primitives and task synchronization mechanisms introduced to aid in modern swift concurrency."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects","kind":"symbol","type":"topic","url":"\/documentation\/asyncobjects"},"doc://AsyncObjects/documentation/AsyncObjects/Future":{"role":"symbol","title":"Future","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Future"}],"abstract":[{"type":"text","text":"An object that eventually produces a single value and then finishes or fails."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Future","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Future"}],"url":"\/documentation\/asyncobjects\/future"}}}